### ISSUE TITLE
Quality 9 and 10 do not work with ETC

### ISSUE THREAD

**Issue by sygmajji** [TimvanScherpenzeel/texture-compressor#14]
Quality 9 and 10 do not work with ETC because the mapping is off. It results in an out of bound error in the quality string array.
There is only 4 items in the quality settings array and quality 10 / 2.1 will give id 4 which is out of bounds.
Another way to handle this could be to map quality numbers directly to a quality setting string with a switch. Something like that (only 3 levels).

```
		// Quality flag
		const qualityOptions = ['etcfast', 'etcslow', 'etcfastperceptual', 'etcslowperceptual'];
		var qualityFlag;
		switch(quality) {
			case 1:
				qualityFlag = qualityOptions[0];
				break;
			case 2:
				qualityFlag = qualityOptions[2];
				break;
			case 3:
			default:
				qualityFlag = qualityOptions[3];
				break;
		}
```

**Comment by TimvanScherpenzeel** [comment]
Thank you for catching this and opening the issue!

Using a value of 2.7 results in a floored range that would be in the 4 element array range and works well enough in my opinion for now.

`console.log(Math.floor(0 / 2.7)); -> 0`
`console.log(Math.floor(1 / 2.7)); -> 0`
`console.log(Math.floor(2 / 2.7)); -> 0`
`console.log(Math.floor(3 / 2.7)); -> 1`
`console.log(Math.floor(4 / 2.7)); -> 1`
`console.log(Math.floor(5 / 2.7)); -> 1`
`console.log(Math.floor(6 / 2.7)); -> 2`
`console.log(Math.floor(7 / 2.7)); -> 2`
`console.log(Math.floor(8 / 2.7)); -> 2`
`console.log(Math.floor(9 / 2.7)); -> 3`
`console.log(Math.floor(10 / 2.7)); -> 3`

**Comment by TimvanScherpenzeel** [comment]
Fixed the issue and added an extra range check for the quality flag. Again, thanks for opening the issue 💯!
