### ISSUE TITLE
S3TC - Default texture encoding

### ISSUE THREAD

**Issue by glegenty** [TimvanScherpenzeel/texture-compressor#20]
Hi ! 
What is the default encoding output for S3TC file, is it RGB ?

**Comment by TimvanScherpenzeel** [comment]
https://github.com/TimvanScherpenzeel/texture-compressor/blob/994afe2ecac0c31e37c7cf98952e4db79891cfba/lib/compressWithS3TC.js#L48

By default it is RGB correct. You will have to pass an `-a` or `--alpha` flag to use RGBA.

From what it looks like `DXT5` and `DXT3` do not respond to the alpha flag, I'm planning to fix that soon.

Most of the info regarding the file formats can be found in the [documentation](https://github.com/BinomialLLC/crunch)

**Comment by TimvanScherpenzeel** [comment]
I've just tried to add `DXT5A` mode but that did not result in the expected result so I'll avoid from adding it. From what I understand from the documentation `DXT5` includes an alpha channel so I'm not so sure what `DXT5A` does specifically (perhaps a separate alpha channel only).
