### ISSUE TITLE
error when using compressed textures in threejs

### ISSUE THREAD

**Issue by siamackSeifi** [TimvanScherpenzeel/texture-compressor#24]
Hi.

I compress needed texture to DXT1 and 5 using following:

`pack({
    type: 's3tc',
    input: 'input/example.jpg',
    output: 'output/DXT1.ktx',
    compression: 'DXT1',
    quality: 'normal',
    verbose: true
}).then(() => console.log('done!'));`

and then load them in threejs using following piece of code:

`
        var boxMaterial = getMaterial('standard');
        var loader = new THREE.KTXLoader();
        var texture = loader.load('/assets/textures/DXT1.ktx');
        boxMaterial.map = texture;
        var box = getGeometry('box', 3, boxMaterial);
        scene.add(box);
`

but when i try to run it in browser i get this warning:

> GL_INVALID_OPERATION: Invalid compressed image size

and texture doesnt get rendered.

the same process works perfectly fine on pvrtc and ETC1.
also with astc, i get RGB and there is no alpha channel ... is it how its supposed to be?

ps: my OS is win10

**Comment by TimvanScherpenzeel** [comment]
Hi @siamackSeifi,

Could you upload the KTX images you generated on here? That way I can have a look at them.

Regarding the implementation in Three.js please have a look at `docs/main.js` to verify if you are loading it in the same way as I am.

For the issue with alpha channel on ASTC I would refer you to the documentation of `PVRTexToolCLI` and `astcenc` you can find online. This library is just a wrapper around those binaries so if you experience issues with the binaries please flag them there.

**Comment by TimvanScherpenzeel** [comment]
Closing this issue due to the lack of response and I think the error is likely to come from the binary itself rather than this wrapper library.
